### ISSUE TITLE
Prediction proposes to use deep features even if not possible, and it fails the job

### ISSUE THREAD

**Issue by grololo06** [ecotaxa/ecotaxa_front#761] opened 2022-01-20 05:08 UTC
If:
- The project has _no_ "SCN Network" in its settings
and:
- User does not notice that the (by default selected) tick:

![image](https://user-images.githubusercontent.com/20199778/150277034-4a03acbf-04b7-4c15-a173-2e327d4035fa.png)
Is not relevant,
then the job fails with error "OSError: SavedModel file does not exist at: /home/ecotaxa/ecotaxa/TF_networks/io_/feature_extractor/{saved_model.pbtxt|saved_model.pb} "

**Comment by jiho** [comment] 2023-05-02 05:59
duplicate of #748

**Closed by jiho** 2023-05-02 05:59 UTC
Labels: bug, page-prediction
